### ISSUE TITLE
Pop Culture Reference Suggestions - Star Wars

### ISSUE THREAD

**Issue by cricksm** [acmbpdc/coding-bootcamp#3]
Please advise on the following perceptions I had on the pop culture ref:

* C-3PO "madness" GIF seems to be giving a negative connotation as the walkthrough begins. Perhaps something more positive so that peeps are able to take it under their swing? 
> Suggested: Luke with a headgear covering his eyes using lightsaber against tiny droid on Millenium Falcon for first time or related theme. 
* Perhaps relating the "power of machine learning" with "the force"? There are very few references to the force here. 
> 
* For train and test, perhaps something from Jedi Training?
> Suggested: Going from padawans to Jedi masters: parallels for both the ML model and the ML programmer? "When I left you I was but the learner, now I am the master"
* Choosing right ML model with "You were the chosen one"?
* Data Science pays a lot - "Be careful not to choke on your aspirations"?
* Poor performing model - "Your powers are weak old man" / "I hate sand" / You have failed me for the last time admiral
* "I don't believe it" - "That is why you fail" when the model is explained but students may have a hard time getting their head around the math.
* "Never tell me the odds" for accuracy rating?

**Comment by kelvindecosta** [comment]
The presence of `.DS_Store` files in the commit prevents a successful pull.

Revert 110dc40 and re-commit without `.DS_Store`

**Comment by kelvindecosta** [comment]
The presence of `.DS_Store` files in the commit prevents a successful pull.

Revert 110dc40 and re-commit without `.DS_Store`

**Comment by cricksm** [comment]
`.DS_Store` has been removed and added to `.gitignore` from the latest commit. If all ok from thy side, close off the issue.

**Comment by kelvindecosta** [comment]
There is still a `.DS_Store` file in the main folder.

Reset to the previous commit and move the `.gitignore` file to the root directory of the repo
