### ISSUE TITLE
[session-07] TODO

### ISSUE THREAD

**Issue by kelvindecosta** [acmbpdc/coding-bootcamp#4]
## Content

@Mohammed-Shoaib, please go through the content. Make any corrections/additions/deletions that you see fit.

I attempted to incorporate both our scripts to make one nice and clean implementation. This may have introduced some bugs that are dormant.

## Theme

@cricksm suggested we use [House M.D.](https://en.wikipedia.org/wiki/House_(TV_series)) as the theme for this week. I think these aligns well with the goals of web scraping.

Feel free to make changes to the session's `README.md` to accommodate this.

Moreover, under the `Usage` section, I thought it would be interesting to see the path from `Web_Scraping` to `Hell`. Instead, change the `end` argument to `House_(TV_series)`

Please run the command and mention the final path.

**Comment by cricksm** [comment]
@kelvindecosta House M.D didn't work out, as it was increasingly difficult to match content with house GIFs and references. Replaced theme with batman instead. Didn't make the second change you had suggested. Advise after review.
